# This is a sample build configuration for Javascript.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: node:5.11.0

pipelines:
  branches:
    master:
      - step:
          script:
            - echo "Running Build and Deploy to Firebase from Master"
            - npm --version
            - npm install -g bower --silent
            - npm install -g grunt --silent
            - npm install -g firebase-tools --silent
            - npm install --silent
            - bower install --allow-root --silent
            - grunt prod
            - firebase deploy --project prod --token "$FIREBASE_TOKEN" --non-interactive
